/*
 Copyright 2014 Nektar Technology, Inc.
*/
loadAPI(2);1<host.getHostApiVersion()&&host.defineController("Nektar","IMPACT LX88","2.0.1","98842bd4-ea69-42b5-a8c6-17b2ad4c2896");host.defineMidiPorts(2,1);host.platformIsWindows()&&host.addDeviceNameBasedDiscoveryPair(["MIDIIN2 (IMPACT LX88)","IMPACT LX88"],["IMPACT LX88"]);host.platformIsMac()&&host.addDeviceNameBasedDiscoveryPair(["IMPACT LX88 Port 2","IMPACT LX88 Port 1"],["IMPACT LX88 Port 1"]);host.platformIsLinux()&&host.addDeviceNameBasedDiscoveryPair(["IMPACT LX88 MIDI 2","IMPACT LX88 MIDI 1"],["IMPACT LX88 MIDI 1"]);
var TRM4N5=!0,TRM4N6=!0,TRM4N7=!0,TRM4N8="LX88",NEKDEBUG=!1,CC={N9T054:12,N9T165:13,N9T278:14,N9T331:15,N9T432:16,N9T585:17,N9T627:18,N9T7E7:19,N9T8E7:20,NBX0A7:21,NBX104:22,NBX2E2:23,NBX304:24,NBX406:25,NBX504:26,NBX608:27,NBX745:28,XC_TRACK_K4TT8:29,N050AZ:30,N052AY:31,N050AW:32,N053AR:33,N050AQ:34,N054AM:35,N050AJ:36,N058AG:37,XC_INST_K4TT0:47,XC_INST_K4TT1:48,XC_INST_K4TT2:49,XC_INST_K4TT3:50,XC_INST_K4TT4:51,XC_INST_K4TT5:52,XC_INST_K4TT6:53,XC_INST_K4TT7:54,XC_INST_K4TT8:55,XC_INST_FADER0:38,
XC_INST_FADER1:39,XC_INST_FADER2:40,XC_INST_FADER3:41,XC_INST_FADER4:42,XC_INST_FADER5:43,XC_INST_FADER6:44,XC_INST_FADER7:45,XC_INST_FADER8:46,XC_INST_K1TT0:56,XC_INST_K1TT1:57,XC_INST_K1TT2:58,XC_INST_K1TT3:59,XC_INST_K1TT4:60,XC_INST_K1TT5:61,XC_INST_K1TT6:62,XC_INST_K1TT7:63,NKX012:108,NKX026:113,NKX027:114,NKX02A:115,NKX035:102,NKX036:103,NKX037:104,NKX038:105,NKX039:106,NKX040:107,NKX041:109,NKX042:110,NKX043:111,NKX044:112};function G4RY(b){sendSysex(b)}
function T1M(b,c,a){sendChannelController(b,c,a)}var CTRL_STATE={ACTIVE:0,MUTED:1,HIGH:2,LOW:3},ST={MIXR_FADRSTART:0,MIXR_CURTRKFDR:8,MIXR_MASTERFDR:9,MIXR_KNOBSTART:10,INST_FADRSTART:20,INST_CURTRKFDR:28,INST_MASTERFDR:29,INST_KNOBSTART:30,NUM_STCONTROLS:40},L04FWindow=3,L04FCtrls=ST.NUM_STCONTROLS,L04FTimerSet=!1,L04FState=new BufferedElementArray(CTRL_STATE.MUTED,L04FCtrls),L04FTimerVal=new BufferedElementArray(0,L04FCtrls);
function L04FEvalInput(b,c,a){var e=Math.abs(c-a)<=L04FWindow;switch(L04FState.values[b]){case CTRL_STATE.MUTED:L04FState.values[b]=e?CTRL_STATE.ACTIVE:c<a?CTRL_STATE.LOW:CTRL_STATE.HIGH;break;case CTRL_STATE.LOW:if(c>a||127===a&&c>=a)L04FState.values[b]=CTRL_STATE.ACTIVE;break;case CTRL_STATE.HIGH:if(c<a||0===a&&c<=a)L04FState.values[b]=CTRL_STATE.ACTIVE;break;case CTRL_STATE.ACTIVE:0>=L04FTimerVal.values[b]&&!e&&(L04FState.values[b]=CTRL_STATE.MUTED)}L04FState.values[b]===CTRL_STATE.ACTIVE&&(L04FTimerVal.values[b]=
3,L04FTimerSet||(host.scheduleTask(L04FTimer,null,250),L04FTimerSet=!0));return L04FState.values[b]}function L04FResetIndex(b){L04FState.values[b]=CTRL_STATE.MUTED;L04FTimerVal.values[b]=0}function L04FReset(){for(var b=0;b<L04FCtrls;b++)L04FResetIndex(b)}function L04FTimer(){for(var b=0;b<L04FCtrls;b++)0<L04FTimerVal.values[b]&&(L04FTimerVal.values[b]-=1);host.scheduleTask(L04FTimer,null,250)}
function onMidi(b,c,a){isNoteOn(b)?onMidiNoteOn(b,c,a):isChannelController(b)?N1ELS(b,c,a):onMidiOther(b,c,a)}function onMidiNoteOn(b,c,a){}
function N1ELS(b,c,a){var e=0,d=0;0<a?N1ELSValOn(b,c,a):N1ELSValZero(b,c,a);uint7ToInt7(a);switch(c){case CC.NKX012:K04TX0FF=0<a;break;case CC.NKX026:MIXER_X0FF=0<a;break;case CC.NKX027:INST_X0FF=0<a;break;case CC.NBX0A7:case CC.NBX104:case CC.NBX2E2:case CC.NBX304:case CC.NBX406:case CC.NBX504:case CC.NBX608:case CC.NBX745:d=c-CC.NBX0A7;0<a&&(c==CC.NBX0A7&&K04TX0FF?(trackBank.scrollTracksPageUp(),L04FReset()):c==CC.NBX104&&K04TX0FF?(trackBank.scrollTracksPageDown(),L04FReset()):TOGGLE_MUTE_X0FF?
trackBank.getTrack(d).getSolo().toggle():trackBank.getTrack(d).getMute().toggle());break;case CC.XC_TRACK_K4TT8:TOGGLE_MUTE_X0FF=0<a;break;case CC.N9T054:case CC.N9T165:case CC.N9T278:case CC.N9T331:case CC.N9T432:case CC.N9T585:case CC.N9T627:case CC.N9T7E7:d=c-CC.N9T054;e=d+ST.MIXR_FADRSTART;CTRL_STATE.ACTIVE==L04FEvalInput(e,a,volume.values[d])&&trackBank.getTrack(d).getVolume().set(a,128);TRM4N7||L04FResetIndex(d+ST.MIXR_KNOBSTART);break;case CC.N9T8E7:TOGGLE_MUTE_X0FF||MIXER_X0FF?(e=ST.MIXR_MASTERFDR,
CTRL_STATE.ACTIVE==L04FEvalInput(e,a,masterVolume)&&masterTrack.getVolume().set(a,128),L04FResetIndex(ST.MIXR_CURTRKFDR)):(e=ST.MIXR_CURTRKFDR,CTRL_STATE.ACTIVE==L04FEvalInput(e,a,selectedVolume)&&cursorTrack.getVolume().set(a,128),L04FResetIndex(ST.MIXR_MASTERFDR));break;case CC.N050AZ:case CC.N052AY:case CC.N050AW:case CC.N053AR:case CC.N050AQ:case CC.N054AM:case CC.N050AJ:case CC.N058AG:d=c-CC.N050AZ;e=d+ST.MIXR_KNOBSTART;CTRL_STATE.ACTIVE==L04FEvalInput(e,a,pan.values[d])&&trackBank.getTrack(d).getPan().set(a,
128);TRM4N7||L04FResetIndex(d+ST.MIXR_FADRSTART);break;case CC.XC_INST_K4TT0:case CC.XC_INST_K4TT1:case CC.XC_INST_K4TT2:case CC.XC_INST_K4TT3:case CC.XC_INST_K4TT4:case CC.XC_INST_K4TT5:case CC.XC_INST_K4TT6:case CC.XC_INST_K4TT7:d=c-CC.XC_INST_K4TT0;if(0===a)break;K04TX0FF?(deviceChain.scrollTo(d),b=deviceChain.getDevice(d),cursorDevice.selectDevice(b)):deviceChain.getDevice(d).toggleEnabledState();break;case CC.XC_INST_K4TT8:TOGGLE_MOD_X0FF=0<a;break;case CC.XC_INST_FADER0:case CC.XC_INST_FADER1:case CC.XC_INST_FADER2:case CC.XC_INST_FADER3:case CC.XC_INST_FADER4:case CC.XC_INST_FADER5:case CC.XC_INST_FADER6:case CC.XC_INST_FADER7:d=
c-CC.XC_INST_FADER0;e=d+ST.INST_FADRSTART;CTRL_STATE.ACTIVE==L04FEvalInput(e,a,cursorEnvs.values[d])&&cursorEnvelope.getParameter(d).set(a,128);TRM4N7||L04FResetIndex(d+ST.INST_KNOBSTART);break;case CC.XC_INST_FADER8:TOGGLE_MOD_X0FF?(e=ST.INST_MASTERFDR,CTRL_STATE.ACTIVE==L04FEvalInput(e,a,masterVolume)&&masterTrack.getVolume().set(a,128),L04FResetIndex(ST.INST_CURTRKFDR)):(e=ST.INST_CURTRKFDR,CTRL_STATE.ACTIVE==L04FEvalInput(e,a,selectedVolume)&&cursorTrack.getVolume().set(a,128),L04FResetIndex(ST.INST_MASTERFDR));
break;case CC.XC_INST_K1TT0:case CC.XC_INST_K1TT1:case CC.XC_INST_K1TT2:case CC.XC_INST_K1TT3:case CC.XC_INST_K1TT4:case CC.XC_INST_K1TT5:case CC.XC_INST_K1TT6:case CC.XC_INST_K1TT7:d=c-CC.XC_INST_K1TT0,e=d+ST.INST_KNOBSTART,CTRL_STATE.ACTIVE==L04FEvalInput(e,a,common.values[d])&&cursorRemoteParameters.getParameter(d).set(a,128),TRM4N7||L04FResetIndex(d+ST.INST_FADRSTART)}}var deferredPlayTime=50;function onMidiDeferredPlay(){transport.play()}
function N1ELSValOn(b,c,a){switch(c){case CC.NKX035:K04TX0FF?transportIsPlaying?(transport.stop(),transport.getPosition().set(transportInPositionValue),host.scheduleTask(onMidiDeferredPlay,null,deferredPlayTime)):transport.getPosition().set(transportInPositionValue):MIXER_X0FF?trackBank.launchScene(0):transport.toggleLoop();break;case CC.NKX036:K04TX0FF?transport.getInPosition().set(transportPositionValue):INST_X0FF?cursorDevice.selectPrevious():MIXER_X0FF?trackBank.scrollScenesUp():transportIsPlaying?
(transport.stop(),transport.rewind(),host.scheduleTask(onMidiDeferredPlay,null,deferredPlayTime)):transport.rewind();break;case CC.NKX037:K04TX0FF?transport.getOutPosition().set(transportPositionValue):INST_X0FF?cursorDevice.selectNext():MIXER_X0FF?trackBank.scrollScenesDown():transportIsPlaying?(transport.stop(),transport.fastForward(),host.scheduleTask(onMidiDeferredPlay,null,deferredPlayTime)):transport.fastForward();break;case CC.NKX038:K04TX0FF?application.undo():MIXER_X0FF?trackBank.getTrack(selectedTrack).getClipLauncher().stop():
transport.stop();break;case CC.NKX039:K04TX0FF?transport.toggleClick():MIXER_X0FF?trackBank.getTrack(selectedTrack).getClipLauncher().launch(0):transport.play();break;case CC.NKX040:K04TX0FF?transport.toggleOverdub():MIXER_X0FF?transport.toggleLauncherOverdub():transport.record();break;case CC.NKX026:K04TX0FF&&application.toggleMixer();break;case CC.NKX027:K04TX0FF&&application.toggleDevices();break;case CC.NKX02A:L04FReset();break;case CC.NKX043:PREV_PATCH_X0FF=!0;INST_X0FF?NEXT_PATCH_X0FF?cursorDevice.isRemoteControlsSectionVisible().toggle():
cursorRemoteParameters.selectPreviousPage(!1):NEXT_PATCH_X0FF?cursorDeviceBrowser.commitSelectedResult():CURSOR_DEVICE_BROWSER_OPEN||(cursorDeviceBrowser.startBrowsing(),cursorDeviceBrowser.getPresetSession().activate(),application.arrowKeyDown());break;case CC.NKX044:NEXT_PATCH_X0FF=!0;INST_X0FF?PREV_PATCH_X0FF?cursorDevice.isRemoteControlsSectionVisible().toggle():cursorRemoteParameters.selectNextPage(!1):PREV_PATCH_X0FF?cursorDeviceBrowser.commitSelectedResult():CURSOR_DEVICE_BROWSER_OPEN||(cursorDeviceBrowser.startBrowsing(),
cursorDeviceBrowser.getPresetSession().activate(),application.arrowKeyDown());break;case CC.NKX041:0===selectedTrack&&(trackBank.scrollTracksPageUp(),L04FReset());cursorTrack.selectPrevious();break;case CC.NKX042:7==selectedTrack&&(trackBank.scrollTracksPageDown(),L04FReset()),cursorTrack.selectNext()}}
function N1ELSValZero(b,c,a){switch(c){case CC.NKX043:PREV_PATCH_X0FF=!1;CURSOR_DEVICE_BROWSER_OPEN&&application.arrowKeyUp();break;case CC.NKX044:NEXT_PATCH_X0FF=!1;CURSOR_DEVICE_BROWSER_OPEN&&application.arrowKeyDown();break;case CC.NKX026:case CC.NKX027:case CC.NKX02A:currentPage!=c&&L04FReset(),currentPage=c}}function onMidiOther(b,c,a){}
var K04TX0FF=!1,MIXER_X0FF=!1,INST_X0FF=!1,TOGGLE_MUTE_X0FF=!1,TOGGLE_MOD_X0FF=!1,PREV_PATCH_X0FF=!1,NEXT_PATCH_X0FF=!1,CURSOR_DEVICE_BROWSER_OPEN=!1,pan=new BufferedElementArray(0,8),volume=new BufferedElementArray(0,8),common=new BufferedElementArray(0,8),cursorEnvs=new BufferedElementArray(0,8),isMacroMapping=new BufferedElementArray(0,8),masterVolume=0,selectedVolume=0,hasDevice=!1,selectedTrack=0,currentPage=CC.NKX026,transportIsPlaying=0;
function nektarinit(){TRM4N5&&host.getMidiInPort(1).createNoteInput(TRM4N8+" Keyboard","8?????","9?????","B?01??","B?40??","D?????","E?????");TRM4N6&&host.getMidiInPort(0).createNoteInput(TRM4N8+" Pads","80????","90????","D0????","E0????");host.getMidiInPort(0).setMidiCallback(onMidi);transport=host.createTransportSection();transport.getPosition().addRawValueObserver(function(a){transportPositionValue=a});transport.getInPosition().addRawValueObserver(function(a){transportInPositionValue=a});transport.getOutPosition().addRawValueObserver(function(a){transportOutPositionValue=
a});transport.addIsPlayingObserver(function(a){transportIsPlaying=a});application=host.createApplicationSection();trackBank=host.createMainTrackBankSection(8,2,1);for(var b=0;8>b;b++){var c=trackBank.getTrack(b);c.getClipLauncher().setIndication(!0);c.addIsSelectedObserver(makeIndexedFunction(b,function(a,b){b&&(selectedTrack=a)}));c.getVolume().addValueObserver(128,volume.setter(b));c.getPan().addValueObserver(128,pan.setter(b))}cursorTrack=host.createCursorTrackSection(2,0);cursorTrack.getVolume().addValueObserver(128,
function(a){selectedVolume=a});cursorDevice=host.createEditorCursorDevice();deviceChain=cursorDevice.getDeviceChain().createDeviceBank(8);cursorRemoteParameters=cursorDevice.createCursorRemoteControlsPage(8);cursorEnvelope=cursorDevice.createCursorRemoteControlsPage("Envelope",9,"env");for(p=0;8>p;p++)cursorRemoteParameters.getParameter(p).addValueObserver(128,common.setter(p)),cursorEnvelope.getParameter(p).addValueObserver(128,cursorEnvs.setter(p));cursorEnvelope.getParameter(8).addValueObserver(128,
cursorEnvs.setter(8));cursorDeviceBrowser=cursorDevice.createDeviceBrowser(0,24);cursorDeviceBrowser.addIsBrowsingObserver(function(a){CURSOR_DEVICE_BROWSER_OPEN=a});masterTrack=host.createMasterTrackSection(0);masterTrack.getVolume().setIndication(!0);masterTrack.getVolume().addValueObserver(128,function(a){masterVolume=a});G4RY("F0 00 01 77 7F 01 05 00 01 13 01 00 6F F7");G4RY("F0 00 01 77 7F 01 05 00 01 14 01 00 6F F7");G4RY("F0 00 01 77 7F 01 05 00 01 15 01 02 6F F7");G4RY("F0 00 01 77 7F 01 05 00 01 0F 01 02 67 F7");
trackBank.scrollToTrack(0);L04FReset()}function nektarexit(){}function makeIndexedFunction(b,c){return function(a){c(b,a)}}function BufferedElement(b){this.value=b}BufferedElement.prototype.set=function(b){this.value=b};BufferedElement.prototype.setter=function(){var b=this;return function(c){b.set(c)}};function BufferedElementArray(b,c){this.values=initArray(b,c)}BufferedElementArray.prototype.setter=function(b){var c=this;return function(a){c.set(b,a)}};
BufferedElementArray.prototype.set=function(b,c){this.values[b]=c};function init(){nektarinit()}function exit(){nektarexit()}
